name: "Cloudflare Enterprise Purge Cache"
description: "Purge a zone's cache via the Cloudflare API"
author: jakejarvis
runs:
  using: docker
  image: Dockerfile
branding:
  color: orange
  icon: trash-2
